NodeOUs:
    Enable: true
    ClientOUIdentifier:
        Certificate: cacerts/ca.bi.paynet-cert.pem
        OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
        Certificate: cacerts/ca.bi.paynet-cert.pem
        OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
        Certificate: cacerts/ca.bi.paynet-cert.pem
        OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
        Certificate: cacerts/ca.bi.paynet-cert.pem
        OrganizationalUnitIdentifier: orderer
